name: FB Confirm Friend

on:
  workflow_dispatch:

 # schedule:
    # Contoh: jalan jam 09:00 WIB (02:00 UTC)
   # - cron: "0 2 * * *"

jobs:
  run-confirm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Confirm Bot
        run: node docs/index.js confirm
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true

      - name: Upload recordings
        uses: actions/upload-artifact@v4
        with:
          name: recordings-confirm
          path: recording_*.mp4
